### ISSUE TITLE
[feature request] Wayward Lantern for v1.18.2

### ISSUE THREAD

**Issue by AngleWyrm10** [AlexModGuy/DomesticationInnovation#96]
Website details an item called the Wayward Lantern, but JEI doesn't show a recipe and the pictured recipe (6 Iron ingots + lantern) doesn't work.

v1.4.2-1.18.2

**Comment by katubug** [comment]
I would like to second (and third through sixth, on behalf of my server mates) this request. My autistic sibling in particular LOVES having pets but is nervous to have any now because their first - a giant Warped Toad named Jason Funderburker - went missing while they were exploring, and we can't find a way to recover him. It breaks my heart not being able to help them out. I'm sorry for the sob story, but I just wanted to express why this is important to me.

Thanks for your time!

**Comment by katubug** [comment]
You're the best! Thank you!
